
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    hostname: homeassistant
    environment:
      - PUID=999
      - PGID=999
      - TZ=America/Toronto
    volumes:
      - /var/containers/homeassistant/config:/config
    ports:
      - 8123:8123 #optional
    # devices:
    #   - /path/to/device:/path/to/device
    restart: unless-stopped

  nodered:
    image: docker.io/nodered/node-red
    container_name: nodered
    hostname: nodered
    ports:
      - 1880:1880
    volumes:
      - /var/containers/nodered/data:/data
    restart: unless-stopped

  mosquitto:
    image: docker.io/eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /var/containers/mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - /var/containers/mosquitto/log:/mosquitto/log

volumes:
  mosquitto_data:
